/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BoardsIndexImport } from './routes/boards/index'
import { Route as TicketsTicketIdImport } from './routes/tickets/$ticketId'
import { Route as BoardsNewImport } from './routes/boards/new'
import { Route as BoardsBoardIdImport } from './routes/boards/$boardId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const TicketsIndexLazyImport = createFileRoute('/tickets/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TicketsIndexLazyRoute = TicketsIndexLazyImport.update({
  path: '/tickets/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/tickets/index.lazy').then((d) => d.Route))

const BoardsIndexRoute = BoardsIndexImport.update({
  path: '/boards/',
  getParentRoute: () => rootRoute,
} as any)

const TicketsTicketIdRoute = TicketsTicketIdImport.update({
  path: '/tickets/$ticketId',
  getParentRoute: () => rootRoute,
} as any)

const BoardsNewRoute = BoardsNewImport.update({
  path: '/boards/new',
  getParentRoute: () => rootRoute,
} as any)

const BoardsBoardIdRoute = BoardsBoardIdImport.update({
  path: '/boards/$boardId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/boards/$boardId': {
      preLoaderRoute: typeof BoardsBoardIdImport
      parentRoute: typeof rootRoute
    }
    '/boards/new': {
      preLoaderRoute: typeof BoardsNewImport
      parentRoute: typeof rootRoute
    }
    '/tickets/$ticketId': {
      preLoaderRoute: typeof TicketsTicketIdImport
      parentRoute: typeof rootRoute
    }
    '/boards/': {
      preLoaderRoute: typeof BoardsIndexImport
      parentRoute: typeof rootRoute
    }
    '/tickets/': {
      preLoaderRoute: typeof TicketsIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  BoardsBoardIdRoute,
  BoardsNewRoute,
  TicketsTicketIdRoute,
  BoardsIndexRoute,
  TicketsIndexLazyRoute,
])

/* prettier-ignore-end */
